<?php

namespace ConnexionBundle\Repository;

/**
 * LogBruteForceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogBruteForceRepository extends \Doctrine\ORM\EntityRepository
{
    public function NbIp($ip)
    {
        $date = new \DateTime('now');
        $qb = $this->_em->createQueryBuilder();
        $qb->select('COUNT(l)')
            ->from($this->_entityName, 'l')
            ->where('l.ip LIKE :ip')
            ->andWhere('l.dateFailure > :maDate  ')
            ->setParameter('ip', $ip)
            ->setParameter('maDate',$date->modify('-1 hour'));

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function clean()
    {
        $date = new \DateTime('now');
        $qb = $this->_em->createQueryBuilder();
        $qb->delete('ConnexionBundle:LogBruteForce', 'l')
            ->where('l.dateFailure <= :maDate ')
            ->setParameter('maDate',$date->modify('-1 hour'));
        return $qb->getQuery()->getSingleScalarResult();
    }
}
