
back:
    resource: "@BackBundle/Controller/"
    type:     annotation
    prefix:   /

connexion:
    resource: "@ConnexionBundle/Controller/SecurityController.php"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
