<?php

namespace BackBundle\Repository;

/**
 * ClassePromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassePromoRepository extends \Doctrine\ORM\EntityRepository
{
}
