<?php

namespace BackBundle\Repository;

/**
 * HistoryClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryClasseRepository extends \Doctrine\ORM\EntityRepository
{
}
