<?php

namespace BackBundle\Repository;

/**
 * refProRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class refProRepository extends \Doctrine\ORM\EntityRepository
{
}
