<?php

namespace BackBundle\Repository;

/**
 * refPedaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class refPedaRepository extends \Doctrine\ORM\EntityRepository
{
}
