<?php

namespace BackBundle\Repository;

/**
 * TechnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnoRepository extends \Doctrine\ORM\EntityRepository
{
}
