<?php

namespace BackBundle\Repository;

/**
 * typeEntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeEntrepriseRepository extends \Doctrine\ORM\EntityRepository
{
}
